### ISSUE TITLE
Ubuntu default client, fails to work?

### ISSUE THREAD

**Issue by tomjridge** [xapi-project/nbd#33] opened 2016-12-10 16:21 UTC
On Ubuntu 15.10, I run the nbd server, then try and connect with the ubuntu "nbd-client". I can expose the remote block device on /dev/nbd0, but when I try to use the device (eg by formatting to ext4) the mkfs command hangs. 

Should I expect this software to work? To work with the particular client ubuntu uses? Some other client?

Any help appreciated!

**Comment by tomjridge** [comment] 2016-12-14 11:37
The client on Ubuntu 15.10 is 3.10; I also tested with nbd-client version 3.14 and get the same behaviour.

The server prints the warning:

WARNING: client doesn't report Fixed_newstyle

but that is all the debug info I could get.

**Comment by gaborigloi** [comment] 2017-07-15 17:11
Thanks for reporting the issue, I could also reproduce this. I think the hang during formatting is due to https://github.com/xapi-project/nbd/issues/41 - when I used the server for read-only access, it worked fine so far.

I think this NBD server should work with any client that follows the [NBD protocol](https://sourceforge.net/p/nbd/code/ci/master/tree/doc/proto.md) and implements fixed or non-fixed newstyle negotiation. (The library itself seems to support the oldstyle negotiation, but the server [doesn't](https://github.com/xapi-project/nbd/blob/master/lib/server.ml#L41)). The warning message that the server printed is a warning about the client, it (probably) means that it doesn't support the fixed newstyle negotiation, only the non-fixed one.

**Comment by gaborigloi** [comment] 2017-07-18 14:00
We're getting there, now in the newest (3.x) version of the NBD server after #43, `mkfs` finishes succesfully without hanging:
```
~/s/new_nbd_client> sudo nbd-client localhost /dev/nbd2 -N ""
[sudo] password for gabori:
Warning: the oldstyle protocol is no longer supported.
This method now uses the newstyle protocol with a default export
Negotiation: ..size = 40MB
bs=1024, sz=41943040 bytes
~/s/new_nbd_client> sudo mkfs.ext4 /dev/nbd2
mke2fs 1.42.13 (17-May-2015)
Creating filesystem with 40960 1k blocks and 10240 inodes
Filesystem UUID: a1131f9b-488d-482b-85df-fe9f60ebe5ad
Superblock backups stored on blocks:
        8193, 24577
Allocating group tables: done
Writing inode tables: done
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done
```
I also managed to manipulate the paritions using `fdisk`, and it can find the partition:
```
~/s/new_nbd_client> sudo fdisk -l
...

Disk /dev/nbd2: 40 MiB, 41943040 bytes, 81920 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x791ceb0f

Device      Boot Start   End Sectors Size Id Type
/dev/nbd2p1       2048 81919   79872  39M 83 Linux
```
However, I failed to mount the partition:
```
~/s/new_nbd_client> sudo mount -t ext4 /dev/nbd2p1 /mnt/test/
mount: wrong fs type, bad option, bad superblock on /dev/nbd2p1,
       missing codepage or helper program, or other error
       In some cases useful info is found in syslog - try
       dmesg | tail or so.
~/s/new_nbd_client> dmesg | tail
[21279.862824] block nbd2: Receive control failed (result -32)
[21279.862939] block nbd2: shutting down socket
[21320.830841] block nbd2: NBD_DISCONNECT
[21327.044827]  nbd2: p1
[21395.252034] EXT4-fs (nbd2p1): VFS: Can't find ext4 filesystem
[21460.480709] block nbd2: NBD_DISCONNECT
[21460.480940] block nbd2: Receive control failed (result -32)
[21474.354043]  nbd2: p1
[21601.706340] evdi: [W] collapse_dirty_rects:102 Not enough space for clip rects! Rects will be collapsed
[21655.255208] EXT4-fs (nbd2p1): VFS: Can't find ext4 filesystem
```

**Comment by gaborigloi** [comment] 2017-07-22 16:46
Actually that warning might be cause by https://github.com/xapi-project/nbd/issues/56 , because it seems that the server may not parse the Fixed_newstyle flag correctly.

**Comment by gaborigloi** [comment] 2017-08-05 16:18
It seems that the NBD server is working, I was just doing something incorrectly when mounting the device. I've tried the above on Debian Jessie, which did not create any `/dev/nbd2p*` files automatically, and it worked fine:
```
$ dd if=/dev/urandom  of=/tmp/test bs=4M count=10
10+0 records in
10+0 records out
41943040 bytes (42 MB) copied, 4.22738 s, 9.9 MB/s
$ nbd-tool serve --debug --verbose /tmp/test
# **********************************
# in a different terminal
$ sudo nbd-client localhost /dev/nbd2 -N export
Negotiation: ..size = 40MB
bs=1024, sz=41943040 bytes
$ sudo mkfs.ext4 /dev/nbd2
mke2fs 1.42.12 (29-Aug-2014)
Creating filesystem with 40960 1k blocks and 10240 inodes
Filesystem UUID: 05d79804-fb18-4f28-a8a0-f43a20ff099d
Superblock backups stored on blocks: 
8193, 24577

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (4096 blocks): done
Writing superblocks and filesystem accounting information: done

$ sudo mount -t ext4 /dev/nbd2 /mnt/test/
$ ls /mnt/test
lost+found/
$ sudo su
# echo test > /mnt/test/test 
# cat /mnt/test/test 
test
# exit
$ sudo umount /mnt/test
$ sudo nbd-client -d /dev/nbd2
disconnect, sock, done
$ sudo nbd-client localhost /dev/nbd2 -N export
Negotiation: ..size = 40MB
bs=1024, sz=41943040 bytes
$ sudo mount -t ext4 /dev/nbd2 /mnt/test/
$ ls /mnt/test
lost+found/  test
$ cat /mnt/test/test 
test
$ ls /dev/nbd2*
/dev/nbd2
```
This worked with both the head of the `master` branch, and version `2.2.0`, therefore I'm closing the issue, thanks for reporting it.

**Closed by gaborigloi** 2017-08-05 16:18 UTC
